# Generated by Django 5.0.1 on 2024-01-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_on', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=False)),
                ('operation_mode', models.CharField(choices=[('normal', 'Normal'), ('standby', 'Standby'), ('custom', 'Custom')], default='normal', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
