# Generated by Django 5.0.1 on 2024-01-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_controller_offline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controller',
        ),
    ]
