# Generated by Django 5.0.1 on 2024-01-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='active',
            field=models.IntegerField(verbose_name='Признак активированности контроллера'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='conn_fw',
            field=models.CharField(max_length=10, verbose_name='Версия прошивки модуля связи'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='controller_ip',
            field=models.URLField(verbose_name='IP адрес контроллера в локальной сети'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='fw',
            field=models.CharField(max_length=10, verbose_name='Версия прошивки контроллера'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='mode',
            field=models.IntegerField(verbose_name='Режим работы контроллера'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='sn',
            field=models.IntegerField(verbose_name='Серийный номер контроллера'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='type',
            field=models.CharField(max_length=10, verbose_name='Тип'),
        ),
    ]
