# Generated by Django 5.0.1 on 2024-01-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('sn', models.IntegerField()),
                ('fw', models.CharField(max_length=10)),
                ('conn_fw', models.CharField(max_length=10)),
                ('active', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('controller_ip', models.URLField()),
            ],
        ),
    ]
