# Generated by Django 5.0.1 on 2024-01-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='interception',
            field=models.BooleanField(default=False, verbose_name='Перехват'),
        ),
    ]
