# Generated by Django 5.0.1 on 2024-01-27 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_controller_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='offline',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='operation_mode',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='power_on',
        ),
        migrations.AddField(
            model_name='controller',
            name='active',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='conn_fw',
            field=models.CharField(default=datetime.datetime(2024, 1, 27, 20, 38, 46, 153850, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='controller_ip',
            field=models.URLField(default=datetime.datetime(2024, 1, 27, 20, 38, 51, 600866, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='fw',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='mode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='sn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
